### ISSUE TITLE
Lost all the tabs on session restore

### ISSUE THREAD

**Issue by yudhir** [photodiode/panorama-view#107]
auto-backup might have helped .

moved to new addon .

**Comment by Ansem93** [comment]
which addon are you using?

**Comment by yudhir** [comment]
Simple Tab Groups . It supports import.

**Comment by Ansem93** [comment]
@photodiode I saw you closed many issues about an autosaving feature. Any hope to see it implemented as an option?

**Comment by photodiode** [comment]
Maybe.
There doesn't seem to be a straight forward way to implement fixed file saving in the background.. if at all.

**Comment by yudhir** [comment]
The addon I use creates a folder in Downloads and saves a backup , probably everyday . It can't read that file back again , i suppose , so there is like ton of back up files .

**Comment by photodiode** [comment]
I had a look at what STG does and it seems very doable.

When testing earlier the backup was always saved it the folder I had saved something to last.
But adding a folder to the filename ("folder/file.ext") seems to always put it in the Downloads folder.
