### ISSUE TITLE
Won't open new tab group

### ISSUE THREAD

**Issue by azmome** [photodiode/panorama-view#109]
I currently have 4 groups containing a total of 66 tabs. If I'm understanding the limits correctly, we can have up to 5 groups and a total of 75 tabs. The Add New Group button in the upper right corner is no longer responding. I've done a forced reload and have restarted Firefox, and have also tried deleting some of my tabs, but the button remains inoperable. Otherwise, this is a great Add On!

**Comment by KittyOh** [comment]
I have the same issue.

**Comment by photodiode** [comment]
I'm guessing the new groups are created underneath the group in the upper left corner.
It's a stupid stupid little bug.. Sorry

**Comment by KittyOh** [comment]
Ah ha! No worries, I'm just grateful the extension exists, it's great :)
