### ISSUE TITLE
Group name text should be single click to edit

### ISSUE THREAD

**Issue by PrototypeNM1** [photodiode/panorama-view#11]
Currently the group name text must be double clicked to edit it.
> It comes from the fact that there is a <span> containing the name (to make the area the same width as the text between two limits) and changes to the text box upon clicking
> But I haven't managed to make it auto select the input box..
> This is also kind of related to the drag area and what is selected on click
\- @photodiode

**Comment by photodiode** [comment]
I might have a go at fixing this this weekend.

**Comment by PrototypeNM1** [comment]
So I investigated this a bit more and realized this is pretty directly the source of two bugs: this and https://github.com/photodiode/panorama-view/issues/10.

I assume you did this to make the space outside of the name drag-able? If that's the case there are some UI issues that are introduced when trying to get that behavior beyond the mentioned bugs.

**Comment by photodiode** [comment]
I think renaming of groups should work as expected now with commit 9fe6b72.
