### ISSUE TITLE
Add options for miniature rendering

### ISSUE THREAD

**Issue by johnkerman** [photodiode/panorama-view#114]
Hello.
With the last update from december, 3rd, design of panorama page was redesigned a bit.
Previously, if pages do not fit in a group well, icons were used instead of thumbnails.
Now, as i understand, behavior was changed to opposite.
I have huge amount of tabs, over 400, so may be its not common issue, but i see site icons 
with thumbnails that are already visible well enough, or i see only ultra-small thumbnails without icons.
Tab title is unnecessary in second case also, cause it trimmed to 3-5 letters.

So, can you please extract this rendering behavior to addon settings, making it possible to return old one?

**Comment by photodiode** [comment]
Hi, sorry about that.
I am working on it right now. I simply forgot to add it back in.
It really does become difficult to use with just the tiny thumbnails.

**Comment by photodiode** [comment]
Fixed with version 0.8.5.
How do you feel about the cutoff size for when the tab title disappears?

**Comment by johnkerman** [comment]
Thanks a lot! Looks much better for me, also ok with tab title.
