### ISSUE TITLE
Pinned tabs closing when original tab group pinned from is closed.

### ISSUE THREAD

**Issue by PrototypeNM1** [photodiode/panorama-view#115]

**Comment by PrototypeNM1** [comment]
Added context, it doesn't seem to recognize a tab as "pinned" and remove it from the tab group until Firefox is closed and reopened. Once recognized as a pinned tab it doesn't seem to close with the tab group, but periodically it seems to close all pinned tabs previously recognized as pinned.

**Comment by photodiode** [comment]
Wow, well that's stupid.
I found several weird bugs with tab pinning, hope I fixed them all.
