### ISSUE TITLE
Can't add a New Group in Panorama screen

### ISSUE THREAD

**Issue by The-Lambs** [photodiode/panorama-view#116]
In Firefox 84.0.1, I can't generate a New Group in the Panorama screen, either by clicking on the Add New Group button (does nothing) or dragging a tab from an existing Group onto the background (it shows the No Entry mouse cursor, and otherwise does nothing). I have all permissions for the extension allowed, and it used to work some weeks back. AFAIK, the only thing different is that Firefox updated several times since the last time I made a new Group.

**Comment by photodiode** [comment]
Can you open the console in the panorama view tab and see if you get an error when creating a new group?

> To open console: Right-click -> Inspect Element -> Select the "Console" tab

**Comment by The-Lambs** [comment]
Ok, thanks to your help I found the problem. Dragging a tab onto the background doesn't automatically create a new group any more, and clicking on the New Group button opened a new group window underneath an existing window, so I had hundreds of group windows all hidden. I could see the window code being added in the console.

I guess this doesn't count as a bug, but perhaps New Group windows should be added in front of all existing Groups?

Thanks for your time!

**Comment by photodiode** [comment]
Thank you
Yes, this is an old "bug" that just doesn't want to go away. I will look into it again.
