### ISSUE TITLE
tab hide is not working

### ISSUE THREAD

**Issue by Pixmi** [photodiode/panorama-view#12]
My browser version is Firefox Developer Edition 59.0b7 (64-bit),

other functions are normal,only tab hide not working.

**Comment by PrototypeNM1** [comment]
You need to enable tab hiding in about:config > extensions.webextensions.tabhide.enabled = true

If that's enabled make sure you have v0.6.19 of Panorama View or newer. If tab hiding still isn't working then there's another issue that would need more investigation as I can confirm tab hiding is working on my system.

@photodiode We should probably leave this issue open until tab hiding is enabled by default in stable. Maybe we can add some kind of label like check-about-config?

**Comment by Pixmi** [comment]
tab hide working now!
extensions.webextensions.tabhide.enabled set to true is correct.
