### ISSUE TITLE
Closing the last tab in a window opens panorama view

### ISSUE THREAD

**Issue by SoWhy** [photodiode/panorama-view#128]
Whenever I close the last tab in a window with multiple tabs, panorama view would open. Normally, it would just switch to the second-to-last tab (which becomes the last tab) which is imho the preferable behavior. Could you change this back to the normal behavior or at least add an option for people like me?

**Comment by photodiode** [comment]
I think this must be a bug.

When did it start happening?

Could you describe, in more detail, exactly what you are doing? ..I can't seem to reproduce it.

**Comment by SoWhy** [comment]
Not much really, I just close an open tab and it happens. Interestingly enough, it only happens, if the panorama view was used once in the window in question before. 

I made a screen grab, I hope it illustrates what happens: https://imgur.com/a/TSgWrgC

In it, I opened three tabs and closed two, which worked normally. Then I restored the tabs, opened panorama view and closed them again, prompting panorama view to open itself. Maybe once panorama view was opened, Firefox thinks it's the last tab and thus switches to it?

**Comment by GeneDot3** [comment]
Happy New Year!  By any chance would you happen to know if the "Panorama Tab Groups" extension is actively being developed anymore?
Thanks,Gene

    On Saturday, January 1, 2022, 10:45:03 PM EST, photodiode ***@***.***> wrote:  
 
 


I think this must be a bug.

When did it start happening?

Could you describe, in more detail, exactly what you are doing? ..I can't seem to reproduce it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SoWhy** [comment]
> Happy New Year!  By any chance would you happen to know if the "Panorama Tab Groups" extension is actively being developed anymore? Thanks,Gene

@GeneDot3 I think you want this project instead: https://github.com/projectdelphai/panorama-tab-groups

**Comment by GeneDot3** [comment]
Thanks, I tried that one - get no response. Thought I'd try here.

    On Sunday, January 2, 2022, 09:33:30 AM EST, SoWhy ***@***.***> wrote:  
 
 



Happy New Year! By any chance would you happen to know if the "Panorama Tab Groups" extension is actively being developed anymore? Thanks,Gene


@GeneDot3 I think you want this project instead: https://github.com/projectdelphai/panorama-tab-groups

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by photodiode** [comment]
> Not much really, I just close an open tab and it happens. Interestingly enough, it only happens, if the panorama view was used once in the window in question before.
> 
> I made a screen grab, I hope it illustrates what happens: https://imgur.com/a/TSgWrgC
> 
> In it, I opened three tabs and closed two, which worked normally. Then I restored the tabs, opened panorama view and closed them again, prompting panorama view to open itself. Maybe once panorama view was opened, Firefox thinks it's the last tab and thus switches to it?
> 
> Edit: This is on Firefox 96.0b10

I did some testing and checking and, as I thought, there is no code determining what tab to make active when the current one is closed. The reason is that hijacking Firefox's default behavior would be pretty difficult.

There seems to be some bug or setting preventing your installation of Firefox from only using only visible tabs when selecting the new tab to activate. I am still unable to make it happen on my computer. A proper new years pickle.

**Comment by photodiode** [comment]
@GeneDot3 
I wouldn't claim this project to be in _active development_, but I do try to keep it limping along. I use it everyday myself so I hardly want it to die.

**Comment by SoWhy** [comment]
> > Not much really, I just close an open tab and it happens. Interestingly enough, it only happens, if the panorama view was used once in the window in question before.
> > I made a screen grab, I hope it illustrates what happens: https://imgur.com/a/TSgWrgC
> > In it, I opened three tabs and closed two, which worked normally. Then I restored the tabs, opened panorama view and closed them again, prompting panorama view to open itself. Maybe once panorama view was opened, Firefox thinks it's the last tab and thus switches to it?
> > Edit: This is on Firefox 96.0b10
> 
> I did some testing and checking and, as I thought, there is no code determining what tab to make active when the current one is closed. The reason is that hijacking Firefox's default behavior would be pretty difficult.
> 
> There seems to be some bug or setting preventing your installation of Firefox from only using the visible tabs when selecting the new tab to activate. I am still unable to make it happen on my computer.
> 
> A proper new years pickle..

I think I found the culprit and it's not your extension. When I disabled this extension https://addons.mozilla.org/de/firefox/addon/select-after-closing-current/ it works correctly. 

So I did some more digging into that extension and it turns out that when it is set to switch to the tab on the right (and you forgot to select "skip hidden"), it will assume panorama view is the "tab" to the right of the closed tab. 

Sorry for wasting your time, I completely missed this extension when disabling potential interfering addons before testing it. 

Keep up the good work 👍

**Comment by photodiode** [comment]
Thank you, that's good to know!
