### ISSUE TITLE
Crash while in panorama view

### ISSUE THREAD

**Issue by mirh** [photodiode/panorama-view#129]
Not immediately, and I cannot really reproduce it, though it happened out of the blue
https://crash-stats.mozilla.org/report/index/b4114cbe-aea6-4ee4-8e66-daa360220110

**Comment by photodiode** [comment]
From the crash report and the related bugzilla entries it seems to be a memory bug, maybe in Firefox. Could it be because you're using a beta version?

**Comment by mirh** [comment]
Don't think so. 
Then, it may even be that it is indeed some memory bug. I certainly have *mountains* of tabs opened. That still shouldn't make anything explode.

**Comment by photodiode** [comment]
I have had this happen when moving tabs between windows and groups.
It might be fixed with all the bug fixing I did in the drag and drop code, but who knows..

**Comment by mirh** [comment]
I don't seem to remember drag and dropping was involved. 
But to be fair it's as well likely that sometimes somehow somewhat there were memory peaks/hotspots/flashes, and those clashed badly with 32-bit firefox more or less normal limitations. https://bugzilla.mozilla.org/show_bug.cgi?id=1749138
