### ISSUE TITLE
[Feature request] Implement import from Panorama Tab Groups

### ISSUE THREAD

**Issue by Slater91** [photodiode/panorama-view#131]
Hi. I just discovered this add-on and it looks great! I have been a user of Panorama Tab Groups for years and I rely on it to get my work done, but unfortunately there is no way to restore groups from that add-on and that means that switching to this one would force me to manually rearrange hundreds of tabs.
A feature to import tabs from that add-on would allow me to make the transition to this extension. Do you believe it would be possible to implement this?

Thank you!

**Comment by photodiode** [comment]
Have you tried loading a backup from Panorama Tab Groups?
It should be using the same format as this add-on.

If not then do you get an error?

**Comment by Slater91** [comment]
Thanks for your reply. I have tried, but without success. The groups were not kept unfortunately, just the list of tabs. I will try again in the coming days to see if any error pops up in the console.

**Comment by photodiode** [comment]
I'm closing this issue as I can't reproduce it. Please try the steps in this comment if it's not working #136 (1430570732)
