### ISSUE TITLE
Scroll bar on narrow tab groups when there shouldn't be

### ISSUE THREAD

**Issue by MikhaD** [photodiode/panorama-view#139]
# Issue
I updated to version 0.9.5 and suddenly there are scroll bars on some of the tab groups. I assume this is unintended behavior as if it was intentional there is no reason for the tabs icons to remain so small.

I suspect the issue stems from the decreased width because of the presence of the scroll bar. The rate at which the tab icons scale means that there is always only enough space for 1 tab per row. When I switch to responsive design mode (Ctrl+Shift+M in FireFox), which has a scrollbar overlay that doesn't take up any width, the issue disappears.

If I set `scrollbar-width: none` the problem also disappears.
# Screenshots
![image](https://user-images.githubusercontent.com/31388146/226384758-923cc831-2a1b-4d40-8291-517e3ebc5c12.png)
![image](https://user-images.githubusercontent.com/31388146/226384948-23e331d7-3846-4a02-a42c-02c7108e67bc.png)

**Comment by photodiode** [comment]
I looked into it and found out that on my PC Gnome GTK uses floating scrollbars.
Turning `widget.gtk.overlay-scrollbars.enabled` off let me witness the horrors above.
Sorry about that.

I did some changes that seem to fixed it and I will have a new version up within a day.

**Comment by photodiode** [comment]
I hope this is fixed with version 0.9.6

**Comment by MikhaD** [comment]
version 0.9.6 has indeed fixed the issue. I appreciate your fast response, and your continued work on this excellent add on. Thank you.
