### ISSUE TITLE
Broken theme

### ISSUE THREAD

**Issue by chaikadev** [photodiode/panorama-view#140]
The add-on looks like this since today.
![image](https://user-images.githubusercontent.com/72362924/226424283-63f4b389-e4c3-4ec0-bbb5-0cc0eed042ba.png)

The bug also happens in the options menu.
![image](https://user-images.githubusercontent.com/72362924/226424629-02086224-250f-4373-82d3-ec4e1be39292.png)

I noticed the issue is fixed if the theme is set to light or dark instead of auto.

**Comment by manchicken** [comment]
I also have this problem. This is the theme I'm using: https://addons.mozilla.org/en-US/firefox/addon/mozilla-mdn-blue-grid/

Manually setting the Theme to light did work around this issue.

**Comment by photodiode** [comment]
That's impressively bad. I tested with a bunch of random themes to try and make something that works but I guess there will always be some themes that are a bit difficult to automatically get right.
I'll look into it a bit more.

For now setting the theme to light or dark in the preferences should do the trick as you say.

**Comment by photodiode** [comment]
Maybe I should add an option for "custom" in the preferences,
one where it tries to color the panorama view using the current theme but falls back to OS Auto when it can't.

**Comment by photodiode** [comment]
Not really, as I know what the problem is, it's just a bit hard to get right.

What I tried to do was read the current theme and use color values from there to color the panorama view, but sometimes themes omit certain values I want to use.

In v0.9.6 there is now a check that aborts and falls back to Auto if needed values aren't provided by the theme.

**Comment by manchicken** [comment]
That's a good idea.

For the record, the amount of multi-tasking I do makes this Firefox extension indispensable for me. Your project makes me much more effective at my job.

**Comment by photodiode** [comment]
Then let's try that!

Thank you, that makes me very happy to hear.

It's really nice to know others use something I made, though uploading new versions is a bit more stressful when there's thousands of people I could have messed something up for, haha.

**Comment by manchicken** [comment]
Yeah, that's part of the gig. I'm also a maintainer, so I feel your pain on this one.

**Comment by manchicken** [comment]
Quick note, the stuff on the side is still invisible. There should be a + button in the upper-right, but I can't get it to show up.

**Comment by photodiode** [comment]
Thank you, I completely forgot about that one.

**Comment by manchicken** [comment]
No worries. I remember where it is supposed to be, and it still works, but it's invisible like a ninja.

**Comment by chaikadev** [comment]
Thank you photodiode!
