### ISSUE TITLE
When I run Panorama View, every tab thumbnail image is still not immediately up-to-date.

### ISSUE THREAD

**Issue by GitHubro5** [photodiode/panorama-view#21]
Hi.

When I run Panorama View, every tab thumbnail image is still not immediately up-to-date.

Thumbnail images aren't updated even though time has passed.
To update the thumbnails to the latest, I first need to select the desired tab and then run Panorama View once more.
However, this only updates the thumbnail image of the selected tab to the latest.
Still other thumbnails of background tabs are not updated.

I compared this issue to Firefox 21.

Of course, the stable Firefox version has not been released yet.
In my memory, I know that in the past Mozilla removed code inside Firefox for these features for security reasons.
In addition, due to the recent moves of Mozilla, which places more emphasis on security than the user's convenience, it seems difficult to expect a tab group environment similar to the 21 version.

Since version 22, it is no longer possible to update thumbnail images in the Tab Group.
Just like the one created by Quicksaver, only the top of each page is displayed as a thumbnail image.
In fact, I can say that version 21 is the last version to support a complete tab group environment. However, there is a problem that some sites are unable to connect due to SSL security error.
In addition, some web pages aren't displayed correctly.
However, in most cases it works fine without problems.

I think browsers with a variety of convenient features are actually faster browsers than simply speed-only browsers.
In fact, in version 21, my work efficiency was much more efficient and fast.
So I realized, and now I have decided to use version 21 until the major issues are resolved.
Of course, in a macOS environment, there is a browser called Safari with this feature, so I do not need to use other inconvenient browsers.

Thank you for your efforts to make the current uncomfortable tab environment more convenient.

**Comment by PrototypeNM1** [comment]
If I understand correctly this will be resolved by https://github.com/photodiode/panorama-view/pull/14.

**Comment by photodiode** [comment]
This is now fixed with the change to captureTab()
