### ISSUE TITLE
Returning to previous tab does not work if Panorama View is open in two windows at once

### ISSUE THREAD

**Issue by andrewguertin** [photodiode/panorama-view#24]
Follow up from [PR 23](https://github.com/photodiode/panorama-view/pull/23#issuecomment-371027126):

If you click the Panorama View button to open it and then click the button again it returns to the last open tab. But if you have two windows open, click it in window A, click it in window B, and then click it in window A again, window A does nothing and window B returns to the last open tab (but with the PV tab still in the tab bar and all other tabs hidden).

This is because when I wrote the code to store the last active tab, I stored it in the background script, and stored only a single tab. If two windows need to store a last active tab, the second one overwrites the first.

-----

There are two ways this could be fixed: 
a) Store the last active tab in the PV content script and retrieve it using the [message passing](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Communicating_with_background_scripts) functionality
b) Continue storing last active tab in the background script, but do so as a map of window ID => tab ID

**Comment by Bareus** [comment]
We might have to use a mix of both: I'm currently looking into #26 and we might have to use message passing to communicate between content and background script. 

It doesn't look like mozilla will fix that bug in `browser.extension.getBackgroundPage()` in the forseeable future, so we might as well completly switch to message passing.

**Comment by andrewguertin** [comment]
I'm working on fixing this.

There's a simple fix (just store it with browser.session.setWindowValue instead of as a background script variable), but I'd like to integrate it with the similar work the tabNodes.js script does to set its highlight and that requires a slightly larger rework.

If anyone needs the simple fix before that's done, it's sitting in the activetab branch in my repository.

**Comment by photodiode** [comment]
Fixed with with commit 50796ed (v0.7.7)
