### ISSUE TITLE
Closing and reopening window loses groups

### ISSUE THREAD

**Issue by andrewguertin** [photodiode/panorama-view#25]
Steps to reproduce:
Create a new window
Create several groups in that window, with tabs in each
Optional: name the groups
Close the window
Reopen the window from History -> Recently Closed Windows

Expected results:
Still have the groups

Actual results:
All the tabs are in one group. If you named the groups, the names are lost.

**Comment by photodiode** [comment]
Will be fixed with next version (v0.7.8)
