### ISSUE TITLE
Icon of browser_action nearly invisible with dark theme

### ISSUE THREAD

**Issue by Bareus** [photodiode/panorama-view#28]
It seems like the color of the browser action icon is not set correctly when using dark theme:

![grafik](https://user-images.githubusercontent.com/6215452/37495899-e3adcf3c-28af-11e8-9924-4548661a2dbe.png)

This bug has probably been introduced in commit `072bbd`. In about:config `svg.context-properties.content.enabled`  is set to `false` by default so not everyone can take advantage of `fill="context-fill"`. Also `context-fill` is [non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-context-properties), so you should either find another solution or revert that commit back.

**Comment by photodiode** [comment]
Before that commit it simply was dark at all times too, so there would  be no difference with reverting back. I did the non-standard way as a quick "hack" until a better solution is made. Sorry about that.
