### ISSUE TITLE
No keyboard shortcuts 

### ISSUE THREAD

**Issue by udovdh** [photodiode/panorama-view#35]
TabGroups keyboard shortcuts appear not to work.
What keyboard shortcuts do work?

**Comment by udovdh** [comment]
See https://support.mozilla.org/en-US/questions/1009024 for TabGroups shortcuts

**Comment by udovdh** [comment]
Please pull commit https://github.com/photodiode/panorama-view/pull/32/commits/dfd5d93e2c10e7cfb0adc3ff845df0c56992ed06 to have at least Alt-W shortcut.

**Comment by projectdelphai** [comment]
This project is currently abandoned/not maintained and I can't currently get access to this project to make any changes or fix any issues. If you need any help and want me to fix any issues or add any features, create an issue in my fork of this project [here](https://github.com/projectdelphai/panorama-tab-groups)!

Shortcuts for switching groups and toggling Panorama View are currently implemented and more are coming :)

**Comment by udovdh** [comment]
Thanks, very interesting fork; please make export/import work and I can start testing!
