### ISSUE TITLE
Tabs moved from one window to another aren't placed into a tab group

### ISSUE THREAD

**Issue by RoboRock81** [photodiode/panorama-view#38]
When dragging a tab from one window to another, the tab is not placed into any tab group in the destination window. The tab then becomes hidden when the Panorama View is opened and is not able to be un-hidden by changing groups. It can only be revealed by searching for the title/URL in the address bar.

**Comment by udovdh** [comment]
Same happens wehn starting FF by clicking a link in e..g. Thunderbird.

**Comment by photodiode** [comment]
This should be fixed with commit 9705783
