### ISSUE TITLE
Alt-W issue

### ISSUE THREAD

**Issue by udovdh** [photodiode/panorama-view#42]
When going through the groups using alt-W I see a group N+1 with just the first TAB of group N.

**Comment by radicalpi** [comment]
There's an issue I noticed, but didn't have a chance to fix where moving the last activated tab from one group to another will keep it as the last active tab for the group its no longer in, so when switching groups, it tries to activate a tab not in its group, so that tab shows both in its group and its former group.

Once you manually focus/activate a tab in each group, it should cycle through the groups properly.

**Comment by udovdh** [comment]
Using the mouse to change groups works OK.
Using Alt-W works as described.

**Comment by udovdh** [comment]
If tab focus is the issue then maybe `remember` the focus from a previous session?

**Comment by photodiode** [comment]
You could use the tab.lastAccessed value to choose which to focus on maybe.

**Comment by radicalpi** [comment]
The previous PR attempts to revert to the first tab in the group if one is not set. It just stores that in a variable and doesn't update it properly if a tab changes groups. I'm not sure if it really needs to remember focused tabs between sessions, but the handling of the last focused tab is a bit buggy. I'll attempt to resolve it soon, if I have a chance.

**Comment by photodiode** [comment]
I fixed all this yesterday with 0.7.7
unless that is what you mean is a bit buggy.
I haven't noticed anything weird yet, though

**Comment by radicalpi** [comment]
Ah, I didn't see that release. Yes, the issue I was aware of looks to be solved. Not sure about the rest of the reported issue above. Cycling seems to behave as one would expect.

**Comment by udovdh** [comment]
Alt-W does not work in Dutch language version of FF as Alt-W is connected to 'BeWerken' (Edit).

**Comment by radicalpi** [comment]
Additionally Alt + W with the find bar active toggles the Whole Words option in English. So it will likely need to be changed to a non Alt shortcut to prevent conflicts with menu items.

**Comment by udovdh** [comment]
I could not get the AddOn towork 100% w.r.t. Alt-W action: I manually focussed/activated a tab in each group yet the behaviour of Alt-W (N+1) did not change.
