### ISSUE TITLE
import script for groups from legacy Tab Groups addon

### ISSUE THREAD

**Issue by DorianScholz** [photodiode/panorama-view#45]
Thanks for the great tab groups extension!
This one made me switch from FF52-esr to FF59.
To port my existing tab groups from the legacy Tab Group addon by Quicksaver I made a small nodejs script to update my profile's sessionstore.js to work with this new addon:
https://gist.github.com/DorianScholz/55c2c538289323be6845949001408eb3

Maybe this helps someone to migrate more easily as well or even can be used as a base for future automatic import functionality...

Use the script like this to convert you tab groups from FF-esr to FF>57:
`node FFTabGroupsConverter.js ~/.mozilla/firefox-esr/MY_PROFILE/sessionstore.js ~/.mozilla/firefox/MY_PROFILE/sessionstore.js`
Make sure to close FF and then delete/rename the `sessionstore-backups` dir as well as the `sessionstore.jsonlz4` file in your profile dir, so on next start FF will import the newly generated `sessionstore.js`.

**Comment by RageYL** [comment]
Hi,

Couldn't import my tabs from ff52-esr but everything seems to work fine with your script. Thank you a lot !
