### ISSUE TITLE
Thumbnail images are not displayed from 20 tabs within a group.

### ISSUE THREAD

**Issue by GitHubro5** [photodiode/panorama-view#46]
Hi.

**Thumbnail images are not displayed from 20 tabs within a group.**
I have attached a photo.
![thumbnail images are not displayed from 20 tabs within a group](https://user-images.githubusercontent.com/14139205/38009008-fea40d60-328c-11e8-9891-101397ec1e7f.png)

**Comment by photodiode** [comment]
I have adjusted this with the latest update. As I finally added resizing of groups you can fiddle with them to your heart's content. ;)
