### ISSUE TITLE
(1) Here are some feedback that I hope will be included in future versions.

### ISSUE THREAD

**Issue by GitHubro5** [photodiode/panorama-view#5]
Hello.

**1. The ability to keep the thumbnail images of all tabs of all groups including current web page scroll position up-to-date immediately.**
In the following two cases, 
(when the user runs the Panorama View extension)
(In real time when the Panorama View extension is running)

**2. The ability to automatically group, arrange and display thumbnails with the same domain into the domain's name group within the current group.**

**3. The ability to close the thumbnail (tab) by clicking the mouse wheel button anywhere on the thumbnail without pressing the X button.**

**4. Function that can be executed using shortcut keys.**

**Comment by photodiode** [comment]
Hi, thank you for the feedback!
1. With the new tabs.captureTab() function coming in v59 this can finally be added, and I plan on doing it as quickly as I can. I've been missing this myself.
2. I am not entirely sure what you mean here, sorry..
3. I will add this. I've found myself trying to click the mouse wheel to close a tab too many times now. Haha
4. Yeah, shortcut keys should also be added.
I am very busy at the moment, so aside from tab hiding and better screenshots, I can't promise much the next month or two. I will put up the code at some point, though. So more people can help add features if they want.

**Comment by GitHubro5** [comment]
Thank you for answer.

This is what I meant in the second paragraph.

There is currently one extension to the Chrome browser called Tabs Manager.
Here is the link.
https://chrome.google.com/webstore/detail/tabs-manager/okeooekaaniggaignhhfeddohlcjadkd?hl=en

As you can see from the pictures, tabs with the same host web address are automatically displayed as a group with their address name.
For example, in the pictures, there are some groups called mail.google.com, facebook.com, and stackoverflow.com, and each group has several tabs that have that address.
If you do not mind, you might want to try the extension once.

In a different way,
In the current macOS Safari browser(since Yosemite), tabs with the same host web address are displayed in stacking order style.
However, the spacing between each tab is so narrow that it is very difficult to distinguish the exact thumbnail image.
In addition, this style is more difficult to distinguish between tabs as the number of tabs increases.

So I think that style like Tabs Manager is better.
Of course, I think both styles have their advantages and disadvantages.
In terms of space savings, Safari seems to be more efficient while the Tabs Manager approach is more intuitive.
I think the stacking order style is also good, if it keep the gap between each tab wide enough

Other than that, there is no search function, so a **tab search function** is also required.

Finally, Is it possible to implement the following feature in the future?
**The Ability to activate the thumbnail(tab) by keeping the mouse cursor over a thumbnail while dragging something.**

In macOS's Mission Control, I can activate the thumbnail by keeping the mouse cursor over a thumbnail while dragging something.
After about 2 seconds, the thumbnail pointed by the cursor is activated.
This is very handy feature when copying, pasting, and moving something in a complex work environment.
Likewise, users will be able to work more easily on complex tab bars environment.

Thanks for your time and effort, and you may share my feedbacks with other developers from many different places.
Rather very welcome.
I will tell you if I have other ideas.
If there is something you do not understand, please let me know.

**Comment by PrototypeNM1** [comment]
1) Should land with https://github.com/photodiode/panorama-view/pull/14
2) That's possible to do but kind of outside of the scope of "necessary features", so unlikely to happen unless a developer becomes interested and runs with it. Adding this kind of feature would also require a bit of thought because it opens a vector for UI additions which can quickly clutter the interface and add code complexity to the project. Any attempt at this would need to think of similar customization features and figure out how to group them while keeping the UI clean. All that to say: it would take a fair bit of work do do well and will require a lot of work.
3) Landed with https://github.com/photodiode/panorama-view/pull/13
4) Issue is being tracker in https://github.com/photodiode/panorama-view/pull/13

**Comment by Rictusempra** [comment]
I would like to vote for the second here.

This feature, together with `browser.tabs.tabhide()`, will bring a nice experience for users who have a trunk of tabs with similar domains. Specifically you can check `tab stack` feature in Vivaldi.
