### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by MIvanIsten** [photodiode/panorama-view#56]
PC was in sleep and restarted due power failure, so firefox was not closed clean.
After firefox start, groups was lost, extension button became irresponsive.
Imported back a previous export, and that failed multiple ways.
- Only the group with lowest ID was filled with tabs. 
The tabs from other groups are not loaded at all. Can't switch to them with ALT-W or CRTL-TAB.
- Group positions was not restored. 
All groups was positioned top-left. When I slightly moved a tab, the tab with next ID  jumped to its proper position.

Repeated the import with `extensions.webextensions.tabhide.enabled = false`, and failed the same way.
Same results with v0.8.0 and v0.8.1

**Comment by photodiode** [comment]
There is clearly something wrong, as several people seem to have had similar problems. Sadly I haven't experienced any of them myself so I am still unsure what is cause it.
I will be doing a clean up and probably rewrite of the whole group handling system since it's become a bit messy. I hope I find the bugs then and get it all fixed and streamlined.

**Comment by orval** [comment]
I have over 500 tabs I want to import. It was silently failing. I tried removing the 5 pinned tabs that I had and then the import worked.

**Comment by BlangTech** [comment]
> I have over 500 tabs I want to import. It was silently failing. I tried removing the 5 pinned tabs that I had and then the import worked.
> EDIT: actually it could be because `tabview-tab` in `extData` is null for the pinned tabs.

Just use this fork [https://github.com/projectdelphai/panorama-tab-groups](https://github.com/projectdelphai/panorama-tab-groups).
I solved the bug for importing pinned tabs there [Commit](https://github.com/projectdelphai/panorama-tab-groups/commit/00359d6d6a59b01f2b78cbe48970802a029833e6)
