### ISSUE TITLE
Cannot create new group with "+" button.

### ISSUE THREAD

**Issue by WegDamit** [photodiode/panorama-view#57]
or any other way (are the others?)

I observed this just today, but it can be broken for longer:
The "+" button to create new groups is inactive, the Theme switcher works.
i have 5 groups, in two rows.
Closing one doesn't help.

How can i provide more infos to help debugging? Console is empty...

**Comment by WegDamit** [comment]
my bad: 
Just found it, the new group was under the top left one. A lot of them...

**Comment by Qantas94Heavy** [comment]
Same thing occurred to me, was very confused by this. Ideally new groups should not overlap with existing ones.
