### ISSUE TITLE
[Question] "Access your data for all websites" permission

### ISSUE THREAD

**Issue by kubecz3k** [photodiode/panorama-view#60]
First of all, addon looks really nice, haven't tested it but it's probably what I'm looking for. 
But I need to ask, is the "Access your data for all websites" permission really needed? I know there is brief description of permissions on the mozzila addon site, but the way how it's formulated makes me unsure which specific description is linked to this permission. 
Thank you!

**Comment by photodiode** [comment]
Hello!
The permission is needed to use the screenshot API for making the thumbnails. I kinda wish it had it's own permission as I don't need to know anything more about the websites, and as you I also get a bit wary when the **Access your data for all websites** is needed.

**Comment by kubecz3k** [comment]
@photodiode thank you for the answer and the work you are doing on the addon!
 I think the way how current permission system works is very bad, almost every plugin in the wild have *Access your data for all websites* permission and that prevents me from using the browser the way I would like the most. Hope Mozilla will fix this issue (diving the permissions to have more smaller more direct ones + allowing for some kind of 'on demand' permission system would be great (like if apps could have toggable options for functionalities that need some permission)

**Comment by kubecz3k** [comment]
+ there should be separate permission for sending the data to the net, since if the plugin cant send anything it probably is less likely the data will leak :P

**Comment by kubecz3k** [comment]
@photodiode could you help me with one more thing? I'm trying to find documentation of <all_urls> permission but its quite impossible for me to find this documentation on https://developer.mozilla.org Is the docs so bad or am I looking in the wrong place?

**Comment by photodiode** [comment]
This is the closest I can find on the subject
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions

**Comment by kubecz3k** [comment]
@photodiode thank you. Shame on Mozzila for such poor docs.
