### ISSUE TITLE
Toggle Panorama View keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by greggilbert** [photodiode/panorama-view#61]
OSX 10.13.4, Firefox 60.0.

The Toggle Panorama View keyboard shortcut doesn't work - hitting ctrl+shift+F does nothing. (I tried some other key combinations and they don't work either.)

Any ideas? Something I can do to help clarify what's happening?

**Comment by mattwellss** [comment]
On Macs, ["ctrl is interpreted as command"](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values), which means the extension is in [contention with Firefox itself](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&redirectslug=Keyboard+shortcuts#w_miscellaneous_2).

WebExts can [update commands](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update), and that power has been [implemented](https://github.com/nyordanov/panorama/commit/ddd2e9ecf266ca7196285e510c6b501042fb0a3d) in a fork of this extension. That said, it's already set to cmd+shift+e, so no need to customize!

**Comment by greggilbert** [comment]
@mattwellss: makes sense, but cmd+shift+E isn't working for me. Control+shift+E doesn't either.

**Comment by greggilbert** [comment]
Gotcha - thanks for clarifying.
