### ISSUE TITLE
TypeError when importing backup

### ISSUE THREAD

**Issue by StoyanDimitrov** [photodiode/panorama-view#65]
Firefox Nightly 62.0a1 (2018-05-21)
Panorama View 0.8.1

The error I get when importing is "TypeError: group.lastMoved is undefined" on groupNodes.js:424

The import is successful but all the groups are on top of each other and the tabs are not visible. Only the first group (id 0) is fine.

**Comment by udovdh** [comment]
Please allow us to test this commit...
