### ISSUE TITLE
ignore pin tabs

### ISSUE THREAD

**Issue by WladyX** [photodiode/panorama-view#7]
Hi,
Can you please add the possibility to ignore the pinned tabs?
It hides them upon changing to a different group, as they "belong" to only one group.

**Comment by WladyX** [comment]
This is also annoying because upon closing the last tab in the current group it switches to other group, because it switches to the last pinned tab, which belongs to other group.
Thank you very much for your support and great addon!

**Comment by PrototypeNM1** [comment]
This is probably a strong candidate for pulling in changes [Totally not Panorama](https://github.com/nyordanov/panorama).

Ping @nyordanov

**Comment by WladyX** [comment]
At first look it seems Totally not Panorama is exactly what I was looking for, thanks!

**Comment by PrototypeNM1** [comment]
@WladyX heads up that nyordanov (the developer of Totally not Panorama) is now collaborating on Panorama View; you'll probably want to stick to Panorama View as we're pulling in changes from Totally not Panorama at the moment.

**Comment by WladyX** [comment]
Thank you very much for this info!
I have both installed, but Panorama is currently disabled, I'll be sure to keep an eye on the changelog and switch when Panorama will inherit the changes from Totally.

**Comment by mikhey** [comment]
I would prefer some sort of preference for this functionality.  I previously used Tab Groups by Quicksaver (https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) loved and definitely miss it too.  Anyway, I have a preference to pinned tabs to always be pinned regardless of what tab group I'm viewing for things like a PM/Time Tracking web app that I want always to be accessible to me quickly.  

Any thoughts on possibly porting over some of the preferences and UI features (where possible)?

This would be something I'd be interested in toying with myself.

**Comment by Goram** [comment]
1. When in a group clicking on the pinned it changes to that group where they are in. 
2. Oddly enough I removed them then from the group and restored them via FF. Now I have them and can change to a non existent group.

**Comment by photodiode** [comment]
Quick fix for this added in commit 140ca7f

**Comment by Goram** [comment]
Very good!

1. The pinned Tab should disappear from the group and reappear in the selected group on unpin. 
2. At the moment if you open the pinned tab on click, the panorama view remains still open and the other tabs in the selected groups are not shown.

**Comment by flops242** [comment]
I would also appreciate adding a dedicated "pinned tabs" group (pull request from @nyordanov), because it's a bit confusing to have them in any other "normal" group.
