### ISSUE TITLE
Tabs Order in Groups

### ISSUE THREAD

**Issue by cvaida** [photodiode/panorama-view#71]
I consistently find that the tabs order in the group active at the moment of closing the browser do not keep their order.
Does anybody else observe this behaviour or is it just something going wonky in my setup?

PS: I did not have time to investigate further, whether that applies also to other groups or not, or what happens exactly.

**Comment by StoyanDimitrov** [comment]
I don't observe such behaviour on my end.

**Comment by kavalanche** [comment]
I have even bigger issue. I sort my tabs thematically into groups and when I restart browser, they are mixed again. It's like it silently stops saving order at some point.

**Comment by cvaida** [comment]
I found the culprit, it was Tab Control add-on which was messing with the tab index in the session data.

Maybe Panorama could implement it's own index order? As it seems some other addons are messing with the tab indexes.

**Comment by kavalanche** [comment]
I don't have Tab Control add-on while I have this problem.

**Comment by cvaida** [comment]
You may have another addon that messes with the tab index. Try disabling all of the other addons and then check again.

**Comment by projectdelphai** [comment]
This project is currently abandoned/not maintained and I can't currently get access to this project to make any changes or fix any issues. If you need any help and want me to fix any issues or add any features, create an issue in my fork of this project [here](https://github.com/projectdelphai/panorama-tab-groups)!

If you still see this issue, feel free to create a new issue over at that repo and i can work on it :)
