### ISSUE TITLE
custom shortcut

### ISSUE THREAD

**Issue by ZTHawk** [photodiode/panorama-view#82]
Could you add the feature to customize the shortcuts.

**Comment by projectdelphai** [comment]
This project is currently abandoned/not maintained and I can't currently get access to this project to make any changes or fix any issues. If you need any help and want me to fix any issues or add any features, create an issue in my fork of this project [here](https://github.com/projectdelphai/panorama-tab-groups)!

The shortcuts are already customizable in the new add-on so this should be fixed for you :)
