### ISSUE TITLE
Saving groups between sessions?

### ISSUE THREAD

**Issue by keeganwitt** [photodiode/panorama-view#92]
I use https://addons.mozilla.org/en-US/firefox/addon/restart-browser1/ to restart from time to time (Firefox doesn't reclaim memory from closed tabs as well as Chrome does), and noticed all my tab groups were removed and all tabs moved back to Unnamed Group.  Is this the expected behavior?

**Comment by surajamin** [comment]
I don't have the restart add-on as @keeganwitt but i noticed the same behavior during a usual restart (I am on MacOS 10.13) - all my groups were removed and all tabs in a Unnamed Group.

**Comment by photodiode** [comment]
Is this still a problem?
I'm closing this because it's so old and might not even be a thing anymore..
