### ISSUE TITLE
Light or Dark theme isn't set, resets to Light upon Firefox restart

### ISSUE THREAD

**Issue by abiel0530** [photodiode/panorama-view#97]

**Comment by nikeee** [comment]
Reason:
The click on the button does not save any state:
https://github.com/photodiode/panorama-view/blob/a844934a9f1d9211d8a5dc42b91547f840db7158/src/js/view.js#L100-L103

I'd create a PR and save the theme in some kind of preferences, but this project seems pretty dead (6 uncommented, open PRs). No sign of the owner. Hard-Forking this project would be a better option IMHO.

**Comment by nikeee** [comment]
Addendum: For me, it would suffice to just set panorama view to dark mode if the browser uses a dark theme. However, I don't know if this is possible using the Addon-API.

**Comment by Qantas94Heavy** [comment]
@nikeee I believe the "Panorama Tab Groups" fork stores the theme setting: https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/

**Comment by str** [comment]
Yes, I think it's time to  talk about forks. @Qantas94Heavy thank you for that one. It also separates the pinned tabs. 

Any other fork around?

**Comment by nikeee** [comment]
Any advice on how to migrate the tab groups?

**Comment by Qantas94Heavy** [comment]
@str There are a couple of others I think but that's the most active one.

@nikeee There should be a "save backup" feature in the addon preferences.

**Comment by photodiode** [comment]
I added a persistent switch in the add-on preferences.
Sorry it took so long...

@nikeee I have looked at that solution, but it seems a bit hard to determine if a theme is actually dark or not.

**Comment by nikeee** [comment]
Why not just drop the option for a dark mode and use the colors provided by [`await theme.getCurrent(/*window id*/)`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent)? I think 90% o fthe users swithcing to the dark version do that because they have the rest of the browser set to dark mode.

**Comment by photodiode** [comment]
I will look into that.
This might be a nice solution for the slight rework on the themes I'm doing.

**Comment by photodiode** [comment]
It seems that using browser.theme.getCurrent() won't work, at least not yet.
All I get is an empty object with no information, and the documentation says why:

> If no extension-supplied theme has been applied to the given window, it will be fulfilled with an empty object.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent

From what I can gather native themes are not yet written using the webextension API and therefor can't be read.

**Comment by nikeee** [comment]
Would it be an option to use the `prefers-color-scheme: dark` media query? It can be matched via CSS or in JS:
```css
@media (prefers-color-scheme: dark) {
  /* dark styles */
}
```

```js
window.matchMedia("(prefers-color-scheme: dark)")
```

If we implement this, we should remove the option to manually toggle the theme.
