### ISSUE TITLE
Constant 1 cpu load

### ISSUE THREAD

**Issue by mallniya** [photodiode/panorama-view#99]
Hi, I've noticed, that disabling addon is reducing 100%+ cpu utilization with one blank tab to normal low values. I guess that's not how it should work.
Firefox 61.0.1.

**Comment by photodiode** [comment]
Closing as it's really old and I can't reproduce.

**Comment by machitgarha** [comment]
Currently this bug seems to be here. Don't know exactly how to reproduce, but it's weird.

Today, I was working, and suddenly my CPU jumped up too much. I tried disabling the extensions, and after disabling Panorama View, CPU slowed down.
